'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
    await queryInterface.bulkInsert('Spots', [{
      ownerId: 1,
      address: '123 Portculis Dr.',
      city: 'Carnelian Bay',
      state: 'California',
      country: 'United States',
      lat: 93.2,
      lng: 1008,
      name: 'Lodge of the Nightingale',
      description: 'Large Lake View home w/ Hot Tub, Pool Table + Guest House',
      price: 692,
      category: 'BeachFront',
    },
    {
      ownerId: 2,
      address: '444 Lakeview Rd.',
      city: 'Lakeport',
      country: 'United States',
      state: 'California',
      lat: 72.7,
      lng: 98.5,
      name: 'Sunrise Shores',
      description: 'Stunning 4 bedroom, 4 full bath with beautiful lake views.',
      price: 378,
      category: 'BeachFront',
    },
    {
      ownerId: 3,
      address: '7001 Holland Ln.',
      city: 'Jenner',
      state: 'California',
      country: 'United States',
      lat: 50.1,
      lng: 126.8,
      name: 'On The Rocks',
      description: 'a Frank Lloyd Wright inspired modern California Ranch w/ subtle Prairie & International architectural design',
      price: 1499,
      category: 'BeachFront'
    },
    {
      ownerId: 4,
      address: '8832 Reindeer Wy.',
      city: 'San Rafael',
      state: 'California',
      country: 'United States',
      lat: 89.3,
      lng: 103.6,
      name: 'Bay View Bungalow',
      description: 'FANTASTIC STUDIO BUNGALOW TUCKED ON A SECLUDED WATERFRONT ENCLAVE!',
      price: 159,
      category: 'BeachFront'
    },
    {
      ownerId: 5,
      address: '1566 Mosshollow St.',
      city: 'Moss Beach',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Walk to the Beach from this Ocean Front Home',
      description: 'Your beachfront escape awaits you.',
      price: 1025,
      category: 'BeachFront'
    },
    {
      ownerId: 1,
      address: '663 Stacey Dr.',
      city: 'San Diego',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Ocean Front Beach Home With Sparkling Pool',
      description: 'An extraordinary opportunity to spend a magical vacation at this incredible ocean front home in.',
      price: 1445,
      category: 'BeachFront'
    },
    {
      ownerId: 2,
      address: '445 Bodega Estates Ln.',
      city: 'Bodega Bay',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Seamist Beach Cottage, Private Beach & Ocean views',
      description: 'Welcome to our beach cottage for the Ultimate Pacific Coast Surf Experience.',
      price: 610,
      category: 'BeachFront'
    },
    {
      ownerId: 3,
      address: '6221 Gary Rd.',
      city: 'Bolinas',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Spectacular Private Oceanfront Retreat',
      description: 'Spectacular oceanfront home with panoramic views from San Francisco, to Stinson, to Duxbury reef. ',
      price: 1200,
      category: 'BeachFront'
    },
    {
      ownerId: 4,
      address: '48 Barbara Dr.',
      city: 'San Diego',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Spectacular, oceanfront & dog-friendly home with patio, sunset views, & hot tub',
      description: 'Youre in store for something truly spectacular at this oceanfront, family- and dog-friendly San Diego home, sitting right on the water in Ocean Beach!',
      price: 907,
      category: 'BeachFront'
    },
    {
      ownerId: 5,
      address: '1519 Cherrypick Ln.',
      city: 'San Diego',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: '9,000 sq ft Celebrity Oceanfront Estate, La Jolla',
      description: 'This contemporary $22MM estate awards stunning Pacific Ocean views creating an Oceanfront Paradise. ',
      price: 3150,
      category: 'BeachFront'
    },
    {
      ownerId: 1,
      address: '8713 Sol View Ct.',
      city: 'Solana Beach',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Oceanfront Coral Reef',
      description: 'Wake up to the waves in this oceanfront 1810 Sq ft condo,  featuring an expansive condo-length patio with plenty of seating for the entire family.',
      price: 429,
      category: 'BeachFront'
    },
    {
      ownerId: 2,
      address: '3317 Seaside Bay Rd.',
      city: 'San Diego',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Crystal`s See the Sea Condo: Hot Tub, Steps to Restaurants & Bars',
        description: 'Crystal`s condo is located in the "SEE THE SEA" Oceanfront Complex right on the boardwalk.',
      price: 363,
      category: 'BeachFront'
    },
    {
      ownerId: 3,
      address: '314 Fortnight Wy.',
      city: 'Fort Bragg',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Sea Cloud - It doesn`t get much better than this..',
      description: 'A luxuriously modern ocean-front home within walking distance to the beach.',
      price: 916,
      category: 'BeachFront'
    },
    {
      ownerId: 4,
      address: '1183 Pierside Ln.',
      city: 'Imperial Beach',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Beachfront Getaway minutes from Coronado',
      description: 'Beachfront living. A beautiful home for rent on the sand, a wonderful Imperial Beach location right between the pier and town center.',
      price: 1100,
      category: 'BeachFront'
    },
    {
      ownerId: 5,
      address: '9833 Canopy Sails Dr.',
      city: 'Oceanside',
      state: 'California',
      country: 'United States',
      lat: 95.4,
      lng: 205.9,
      name: 'Oceanside Pier 2 Bedroom Deluxe',
      description: 'An enclave for surfers, artists, and beachgoers, Oceanside has the benefit of year-round sunny weather and warm Southern California breeze.',
      price: 223,
      category: 'BeachFront'
    },
      {
        ownerId: 1,
        address: '6718 Everglades Canyon Dr.',
        city: 'Moss Beach',
        state: 'California',
        country: 'United States',
        lat: 95.4,
        lng: 205.9,
        name: '60 Feet Stunning OceanFront 1 Bedroom Malibu Condo',
        description: 'Take your step right into Pacific ocean from this cozy oceanfront unit. It doesnt get closer than this!',
        price: 529,
        category: 'BeachFront'
      },
      {
        ownerId: 2,
        address: '515 Cinder Glade Ave.',
        city: 'Florence',
        state: 'Oregon',
        country: 'United States',
        lat: 95.4,
        lng: 205.9,
        name: 'An Octopus` Garden, A Classic 50`s Cottage',
        description: 'This is a classic and historic 50s cottage.  It may be small but it is cozy and has a gigantic view of the ocean and beach.',
        price: 213,
        category: 'BeachFront'
      },
      {
        ownerId: 3,
        address: '998 Sutter Dr.',
        city: 'Bandon',
        state: 'Oregon',
        country: 'United States',
        lat: 95.4,
        lng: 205.9,
        name: 'Two adjacent beachfront condos w/ gorgeous ocean views - dogs are OK!',
        description: 'Experience a spectacular setting on the ocean shores of Bandon at these two adjacent beachfront condos.',
        price: 427,
        category: 'BeachFront'
      },
      {
        ownerId: 4,
        address: '33 Azalea Rd.',
        city: 'Imperial Beach',
        state: 'California',
        country: 'United States',
        lat: 95.4,
        lng: 205.9,
        name: '1 Bedroom on the Sand',
        description: 'The Sandcastle is a 4-plex, that sits right on the sand.',
        price: 192,
        category: 'BeachFront'
      },
      {
        ownerId: 5,
        address: '593 Alexandria Ct.',
        city: 'Dana Point',
        state: 'California',
        country: 'United States',
        lat: 95.4,
        lng: 205.9,
        name: 'Stunning Ocean Front Luxury Home, Private Beach',
        description: 'Stunning Ocean Front Luxury Home Perfect for Family Reunions, Sleeps 12 Welcome to the perfect luxury retreat!',
        price: 643,
        category: 'BeachFront'
      },
    {
      ownerId: 1,
      address: '444 Brubac St.',
      city: 'Austin',
      state: 'Texas',
      country: 'United States',
      lat: 69,
      lng: 5001,
      name: 'The Bloomhouse by Lodgewell>>Fairy Tale Escape',
      description: 'Come take a vacation from the real world of right angles and ticky tacky boxes. ',
      price: 658,
      category: 'OMG!',
    },
    {
      ownerId: 2,
      address: '6655 Pennywise Rd.',
      city: 'Bend',
      state: 'Oregon',
      country: 'United States',
      lat: 60000,
      lng: 60060,
      name: 'Private Luxury Cabin on Tumalo Lake near town',
      description: 'Gorgeous 3 bed/3.5 bath/2000 SF luxury cabin, sleeps 8',
      price: 299,
      category: 'Cabins'
    },
    {
      ownerId: 3,
      address: '71 Piedmont Circle Wy.',
      city: 'Kootenay Boundary E',
      state: 'British Columbia',
      country: 'Canada',
      lat: 45000,
      lng: 45060,
      name: 'Second Breakfast Hideaway',
      description: 'An authentic earthhouse and hobbit themed inspired fantasy escape.',
      price: 295,
      category: 'Earth Homes',
    },
    {
      ownerId: 4,
      address: '305 New Castle ln.',
      city: 'Newry',
      state: 'Maine',
      country: 'United States',
      lat: 7000,
      lng: 73060,
      name: 'The Glen House at Sunday River',
      description: '9 Bdrm Estate Sleep 26 Movie Theater,Pool,Golf,Ski',
      price: 2608,
      category: 'Mansions',
    },
    {
      ownerId: 5,
      address: '1331 Hooky St.',
      city: 'Pacifica',
      state: 'California',
      country: 'United States',
      lat: 81000,
      lng: 6060,
      name: 'Luxury Beachfront Penthouse Near SF (Blue Wave 3)',
      description: 'Leave your worries behind as you step into this exquisite beach-front sanctuary just minutes from San Francisco.',
      price: 349,
      category: 'Amazing views',
    },
    {
      ownerId: 1,
      address: '410 Veritas Ave',
      city: 'Joshua Tree',
      state: 'California',
      country: 'United States',
      lat: 91000,
      lng: 9060,
      name: 'The Kellogg Doolittle House',
      description: 'This is the famous Kellogg Doolittle estate in Joshua Tree California.',
      price: 7700,
      category: 'Luxe',
    },
    {
      ownerId: 2,
      address: '272 Borger Thoroughfare',
      city: 'Biras',
      state: 'Nouvelle-Aquitaine',
      country: 'France',
      lat: 1000,
      lng: 11360,
      name: 'Chateau Du Campe',
      description: 'This magnificent 15th Century Perigordian Hotel Chateau is set in almost 20 acres of grounds.',
      price: 3007,
      category: 'Castles',
    },
    {
      ownerId: 3,
      address: '814 Glancing Dr.',
      city: 'Trenton',
      state: 'Georgia',
      country: 'United States',
      lat: 100055,
      lng: 113676,
      name: 'Whippoorwill Retreat Treehouse',
      description: 'Whippoorwill Retreat is nestled in treetops on Sand Mountain, 20 min. from Chattanooga, Tn.',
      price: 390,
      category: 'Treehouses',
    },
    {
      ownerId: 4,
      address: '94 Spader Ct.',
      city: 'La Grange',
      state: 'California',
      country: 'United States',
      lat: 10435,
      lng: 11876,
      name: 'Farm Stay at the Bell-Zwart Lodge',
      description: 'Getaway to the Bell-Zwart Lodge located on a working cattle ranch in La Grange, CA. ',
      price: 168,
      category: 'Countryside',
    },
    {
      ownerId: 5,
      address: '717 Banana Spider Wy.',
      city: 'Montara',
      state: 'California',
      country: 'United States',
      lat: 1235,
      lng: 1976,
      name: 'Plywood Marvel',
      description: 'Surrounded by peace and quiet this indoor-outdoor living modern beach home by-the-Sea is the perfect getaway for everyone',
      price: 408,
      category: 'Design',
    },
    {
      ownerId: 1,
      address: '888 Montrose Rd.',
      city: 'Groveland',
      state: 'California',
      country: 'United States',
      lat: 123335,
      lng: 19756,
      name: 'The Pine Mountain Lakehouse near Yosemite',
      description: 'The Lakehouse is an idyllic 4-BR, 3-bath cabin nestled on the shores of Pine Mountain Lake.',
      price: 565,
      category: 'Lakefront',
    },
    {
      ownerId: 2,
      address: '2181 Spevy Rim Ave.',
      city: 'Joshua Tree',
      state: 'California',
      country: 'United States',
      lat: 123335,
      lng: 19756,
      name: 'White Casita, Twins Resort of Joshua Tree',
      description: 'Beautiful modern style home in the desert with gorgeous heated infinity pool.',
      price: 1055,
      category: 'Amazing pools',
    },
    {
      ownerId: 3,
      address: '900 St. Peter Crossing',
      city: 'Breckenridge',
      state: 'Colorado',
      country: 'United States',
      lat: 171335,
      lng: 26756,
      name: 'Big Blue Trace',
      description: 'Big Blue Trace is a brand new gorgeous 5 bedroom home with 4.5 baths and plenty of room to comfortably accommodate up to 10 guests.',
      price: 915,
      category: 'Skiing',
    },
    {
      ownerId: 4,
      address: '55 Fiddlesticks Wy.',
      city: 'Ione',
      state: 'California',
      country: 'United States',
      lat: 174435,
      lng: 26916,
      name: 'PT Ranch House',
      description: 'Enjoy country elegance while staying in  this 1850s farm house.',
      price: 285,
      category: 'Farms',
    },
    {
      ownerId: 5,
      address: '783 Chartruce Dr.',
      city: 'Los Gatos',
      state: 'California',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'Amazing for Silicon Valley business/small families',
      description: 'Our home is in the ideal location of Silicon Valley near major tech companies.',
      price: 79,
      category: 'Private rooms',
    },

    //HERE!!!
    {
      ownerId: 1,
      address: '812 Mossy Hollow Ave.',
      city: 'Topanga',
      state: 'California',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'ShangriLaLa Tiny House Mountaintop Getaway',
      description: 'Elegant and simple.',
      price: 300,
      category: 'Tiny homes',
    },
    {
      ownerId: 2,
      address: '663 Greaves Ct.',
      city: 'Idyllwilde-Pine Grove',
      state: 'California',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'Glamping Dome in Nature-Read Details First-4WD!',
      description: 'Join us in the forest for a beautiful, unique experience.',
      price: 185,
      category: 'Domes',
    },
    {
      ownerId: 3,
      address: '594 Julius Rd.',
      city: 'Westcliffe',
      state: 'Colorado',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'The Hut on Humboldt',
      description: 'Cabin on 110 acres back to national forest.',
      price: 199,
      category: 'National Parks',
    },
    {
      ownerId: 4,
      address: '344 Happy Holly Ln.',
      city: 'Sonoma',
      state: 'California',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'Exquisite French Inspired Chateau',
      description: 'Chateau de Ninis is an exquisite French Inspired Chateau perched at the top of a hill overlooking miles of beautiful Vineyards.',
      price: 4050,
      category: 'Vineyards',
    },
    {
      ownerId: 5,
      address: '2286 Justice Dr.',
      city: 'South Lake Tahoe',
      state: 'California',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'Lakeland Village #611 Lakefront Contemporary',
      description: 'Just remodeled in 2021, this beachfront beauty is one of Lakeland Villages finest.',
      price: 1086,
      category: 'Lake',
    },
    {
      ownerId: 1,
      address: '3822 Dorris Rd.',
      city: 'Mohave County',
      state: 'Arizona',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'MyHappyPlace Dome',
      description: 'Reconnect with nature at this unforgettable escape.',
      price: 129,
      category: 'Off-the-grid',
    },
    {
      ownerId: 2,
      address: '8504 Fanny Wind St.',
      city: 'Tahoma',
      state: 'California',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'Little Bear Log Cabin',
      description: 'Our Little Bear Cabin is perfectly located a very short walk to the beach.',
      price: 200,
      category: 'Ski-in/out',
    },
    {
      ownerId: 3,
      address: '430 Chester Spirit Ave.',
      city: 'Gib Harbor',
      state: 'Washington',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: '38 Yacht equipped with luxury and kayaks!',
      description: 'Have a magical stay on the water in this wood-clad 38 boat: Gollywobbler.',
      price: 200,
      category: 'Boats',
    },
    {
      ownerId: 4,
      address: '77 Sporemund St.',
      city: 'Lake Arrowhead',
      state: 'California',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'A-Frame of Mind - Lake Arrowhead - Lake View & AC',
      description: 'On top of the mountains and beneath the stars, a dramatically unique mountain A-Frame getaway awaits your arrival.',
      price: 307,
      category: 'A-frames',
    },
    {
      ownerId: 5,
      address: '4466 Montrose Abbey Wy.',
      city: 'Tempe',
      state: 'Arizona',
      country: 'United States',
      lat: 174635,
      lng: 2691176,
      name: 'arthouse 1312 - room 3',
      description: 'Welcome to my sanctuary for creative people and artistic-minded professionals alike :)',
      price: 54,
      category: 'Creative spaces',
    },
  ], {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Spots', null, {});
  }
};
